name: shopping_cart_dart
description: A simple shopping cart API in Dart
environment:
  sdk: ">=3.9.4 <4.0.0"
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.0.0
  shelf_modular: ^2.1.0
  json_annotation: ^4.10.0
dev_dependencies:
  build_runner: ^2.11.1
  json_serializable: ^6.12.0
  test: ^1.29.0
